FROM java:8-alpine
MAINTAINER Your Name <you@example.com>

ADD target/helping-hands-service-0.0.1-SNAPSHOT-standalone.jar /helping-hands-service/app.jar

EXPOSE 8080

CMD ["java", "-jar", "/helping-hands-service/app.jar"]
